version: '3'

services:
  openldap:
    build:
      context: ../
    ports:
      - "389:389"
      - "636:636"
    environment:
      - "DEBUG_LEVEL=1"
      - "DOMAIN=example.com"
      - "ORGANIZATION=example"
      - "PASSWORD=123"
      - "INIT_SCRIPT=/var/init/init.ldif"
      - "CUSTOM_SCHEMAS=/var/schemas"
      - "SCHEMAS=cosine inetorgperson nis samba"
    volumes:
      - "./init.ldif:/var/init/init.ldif"
      - "./schemas:/var/schemas"