apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldap-service
spec:
  type: NodePort
  ports:
    - port: 3890
      nodePort: 30890
      targetPort: 3890
  selector:
    app: ldap
